[package]
name = "renderer"
version = "0.1.0"
edition = "2024"

#[dependencies.ash]
#git = "https://github.com/ash-rs/ash.git"
#rev = "c9292cf1b3fb70e4416fe9c47d6d938bd80d52b4"

#[dependencies.ash-window]
#git = "https://github.com/ash-rs/ash.git"
#rev = "c9292cf1b3fb70e4416fe9c47d6d938bd80d52b4"

[dependencies]
ash = "0.38.0"
ash-window = "0.13.0"
bytemuck = { version = "1.23.2", features = ["derive"] }
color-eyre = "0.6.5"
env_logger = "0.11.8"
glam = { version = "0.31.0", features = ["bytemuck"] }
image = "0.25.6"
log = "0.4.27"
presser = "0.3.1"
raw-window-handle = "0.6"
rust-embed = "8.7.2"
smallvec = "1.15.1"
thiserror = "2.0.15"
vk-mem = "0.5.0"
winit = { version = "0.30", default-features = false, features = ["rwh_06"] }

[build-dependencies]
bytemuck = "1.21.0"
color-eyre = "0.6.3"
log = "0.4.22"
naga = { version = "28.0.0", features = ["wgsl-in", "spv-out"] }
shaderc = "0.10.1"
